public enum TipoToken {

    MAS, MENOS, PRODUCTO, ENTRE,

    MENORQUE, MENORIGUAL, MAYORQUE, MAYORIGUAL, IGUALIGUAL, DISTINTO,

    AND, OR,
    IGUAL, INVERSOR,

    IZQ_PARENTESIS, DER_PARENTESIS,
    COMA, PUNTO_COMA,
    IZQ_LLAVE, DER_LLAVE, PUNTO,

    IDENTIFICADOR, NUMERO, CADENA,
    PRINT, IF, WHILE, FOR, FUN, VAR, RETURN, ELSE, NULL, TRUE, FALSE,

    EOF,

    INT, FLOAT, DOUBLE,

}


